### ISSUE TITLE
Document Python API?

### ISSUE THREAD

**Issue by mlissner** [fritz-hh/OCRmyPDF#114]
I could be wrong, but I haven't been able to find documentation for the command itself. Either for the command line API nor for the Python API that looks like it might be coming in 3.0. 

Am I blind? If not, this would be great to get. If so, my apologies! 

Looks like a great project.

**Comment by jbarlow83** [comment]
You can run `ocrmypdf --help` in 3.0, which prints documentation from main.py.

I believe it's `./OCRmyPDF.sh -h` for 2.x.

There isn't really a Python API as yet in 3.0. To be precise, it's not set up so that you can import the ocrmypdf package and then write a Python script for your own custom pipeline. If you want to do something custom, you'd have to edit the ocrmypdf source files yourself. In future releases I will probably move the code in a direction that makes it unnecessary.

For now, I set it up as an importable package is that the Python packaging machinery is for ease of distribution: `pip install ocrmypdf` is all it should take for someone who has previously installed 2.x.
