### ISSUE TITLE
How do you like the idea to start program documentation in the Github Wiki ...

### ISSUE THREAD

**Issue by Wikinaut** [fritz-hh/OCRmyPDF#119]
... on https://github.com/fritz-hh/OCRmyPDF/wiki ?

Would you like me to start a documentation ?

**Comment by jbarlow83** [comment]
I'm going to move the project to https://github.com/jbarlow83/OCRmyPDF because the admin (fritz-hh) never gave me full access to the repo and has stopped responding to emails, so I can't change some things I want to change. So that would be the place to start a wiki.

If you want to start, by all means go for it. What sort of things do you think most need to be documented?

**Comment by Wikinaut** [comment]
@jbarlow83 thanks for the info of your fork, will follow that.
