### ISSUE TITLE
Fine tune word vertical Placement and vertical size

### ISSUE THREAD

**Issue by fritz-hh** [fritz-hh/OCRmyPDF#45]

**Comment by KyleBruene** [comment]
I would like to work on this a bit since most of my PDF's end up with the characters being a few pixels lower than the actual text. Could you point me in the right direction?

**Comment by jbarlow83** [comment]
Positioning is done in hocrTransform.py. My wild guess is that we're somehow not accounting for the baseline offset from the bottom of the glyph. There is an option to turn on bounding boxes and also render the OCR text instead of the image, which may help with seeing if there is a consistent positioning error. There will be a fundamental limit to accuracy though because we just assume the font is Helvetica and stretch/compress it to fit each word. I recommend basing changes on the develop branch since it contains other fixes, and well, it's the latest.

Depending on your application you might want to use Tesseract 3.03 to generate the single page OCR PDFs rather than hocrTransform. Tesseract has other problems with how it renders PDFs, but I think its text positioning is more accurate.

**Comment by fritz-hh** [comment]
Hi kyle,

I started working a long time ago on this. It was already working quote
well for Latin glyphs. If I remember well, my working is in one of the
experimental branches. You can use this as a starting point.

Kingd regards,

Fritz.

**Comment by jbarlow83** [comment]
You'll find this is much improved in OCRmyPDF v3.0-rc2 with the `--pdf-renderer tesseract` flag set.
