### ISSUE TITLE
rewrite ocrmypdf in python 3.4

### ISSUE THREAD

**Issue by fritz-hh** [fritz-hh/OCRmyPDF#94]

**Comment by zorglups** [comment]
I would love this too. I'm currently working on your sh but would much prefer invest my efforts in python. Did you start it ?

**Comment by fritz-hh** [comment]
No I didn't. In fact I am quite busy with other things...
But do not hesitate to contribute through pull requests

**Comment by jbarlow83** [comment]
Yes. I just updated my fork with my latest changes. It is a fork at this
point, really. The project's not terribly active so I haven't made an
effort to keep things separate.

Only the per-page process is in Python at this point.

I've added a number of other changes and fixes as well. In particular, I
added Ghostscript for page rendering (it does a much better job than
pdftoppm), and started work on a feature to insert the OCR layer without
modifying the original content (e.g. for OCR on documents that contain
non-text vector features). I also updated to ghostscript 9.14+'s improved
color engine for PDF/A.

**Comment by zorglups** [comment]
Hello Guys,

I'm not a Python Guru (rather Perl guru) but usually, when I do thing, it is not too bad ;-)
I can concentrate on this 2h30 per week (while waiting my boy at the sport.
I need this and would prefer to collaborate instead of forking the thing and continue on my own.

How do you suggest we proceed ?

I'm volunteer to handle the python port of OCRmyPDF.sh (starting from the one found in the 3.x branch).

The things that annoy me are:
- Frit-hh might still implement fixes in 1.x and 2.x branches so please tell me which is the latest OCRmyPDF.sh to start from.
- jbarlow83 did a fork and it might be worth pull before we continue together.

For information:
1) I made another Python script (that can be made generic based on regex) that watches a folder (based on filesystem notifications (and a first listing)) and handles 'suites' of files (for example: <BROTHER_000043.jpg> <BROTHER_000043_2.jpg> <BROTHER_000043_3.jpg> <BROTHER_000043_4.jpg>) and once the suite is complete (no further write for X seconds, it fires the OCRmyPDF.sh with the list of files as argument. Having OCRmyPDF.sh handle a suite of images is for me a must.
2) I (with or without you   :-/   ) ported OCRmyPDF.sh to python and made it accept suites of images. I will also add an option to have the OCRed text saved as a txt "side car" file to the PDF. I might also save a lightweight jpg sidecar file. All my files will be outputted to a folder (PDF_to_file)
3) I will then make a third script that will feature a web interface and will list the files (with preview of the sidecar jpg) present in the PDF_to_file directory and will:
--- analyse the txt sidecar file and make the best guess on the document date. This will be used as metadate of the pdf as well as prefix for the filename.
--- Based on regular expressions in a first phase and later on on Bayes algorithms, digest the sidecar txt file and suggest tags for the file and deduce as well a filename. This will go through a learning process but will be better than having to do everything manually ;-)   If allowed by PDF/A, I would inject the tags inside the PDF.
--- Once the user acknoledged/corrected the tags on the document, the file will be moved with the final filename to my library folder. All files will sit in this folder and I will probably create a set of folder/subfolder combinations and put in subfolders symlinks to the document laying in the library root so that, with a single file explorer, I'll be able to browse my library by tags. I want this because I use a lot synology access using DSFile and sync my library accross several computer. I do not want to rely on a database to find my files back. 
At any time, I will be able to quickly erase the whole forrest and from all files in the root, recreate the directories and symlinks.

Example: If I have 3 tabs TA, TB and TC and one document FA which has TA and TC tags, I will end with this forest:

/FA
/TA/FA -> /FA
/TA/TC/FA -> /FA
/TC/FA -> /FA
/TC/TA/FA -> /FA

How do you want me to proceed ?

Best regards,

Pierre

**Comment by jbarlow83** [comment]
> jbarlow83 did a fork and it might be worth pull before we continue together.
Not much has really happened in the main branch, by comparison. The functional changes are removing the reportlab monkey patch (which I did later in my fork), and introducing "skip text pages" which was a cherry pick from my fork. 

My fork has the bulk of the conversion to Python 3 done, and a number of robustness improvements. I've tested it on a few thousand files now.

I used ruffus, a library that builds a Makefile-style dependency graph and runs tasks calculate the output. It will use multiple cores to run individual tasks, which gives a speed up particularly for a PDF with fewer pages than the number of cores available. Like `make` it can reuse dependencies from a previous run if desired (e.g. if you keep intermediate files around and change one page, only that page would be re-OCRed). Ruffus also makes it pretty straightforward to connect new bits of functionality to the main pipeline (e.g. taking images instead of PDF input, generating text as output).

I also changed the way PDF/A is handled to avoid the deprecated Ghostscript flag -dUseCIEColor which can cause some colorspace conversion problems (apparently it's most noticeable with shadows). The new way they do it is extremely awkward since you have to feed it a little bit of PostScript and the hardcoded path to an ICC profile. I don't know why the Ghostscript decided to make the interface so much harder to use, but there it is. I don't know how to obtain the path to the ICC file in a multi-platform way. So I broke platform compatibility here with everything except OS X.

I'd recommend merging the fork, rewriting OCRmyPDF.sh to Python 3 (with it still calling ocrpage.py in a subprocess), and then merging the two Python scripts so that they could use a single ruffus pipeline. 

> 1) File system watching and suite of images.
Sounds fun. I would use that. (But please use an "inotify" type service not polling the file system.)

> 3) Web interface
This sounds quite interesting too, but I'd consider making it a separate project. It seems to be functionally orthogonal to creating OCR PDFs. PDF/A does support a keywords field and I believe also supports an XML-XMP file that can contain somewhat arbitrary information.

**Comment by zorglups** [comment]
Thanks for the detailed explanation. If I understand correctly, you concentrated on ocrpage.py and suggest I do OCRmyPDF.py

I agree to leave those 2 scripts separated and merge them at some point later on. 
In my workflow, speed is not a must. (See my workflow explained here below)

If the fork cannot be done in the next week, I'll start working on the OCRmyPDF.py that was started in the branch 3.x. Unless you or Fritz propose something else. 

My scan folder process use notification and not polling. It just polls once the folder upon startup then listen. 

The web interface will be a separate project. 
 
My workflow is the following:
1) Ingest
Most documents are paper documents (A4) ingested thanks to a Brother printer equipped with a duplex feeder and able to write on a smb or ftp. It does not need any PC and I can create kind of bookmarks on the printer dashboards to create jpg in a folder, PDFs in another one, send a pdf/a to my mail, ... Quite flexible. This was key to go paperless. Whenever I want to file a paper, I just feed it to the feeder and can then put it to the trash. Anything that must be filed (except things like kids drawings :-) ) is written as 200 or 300 dpi jpg to ftp. The Brother can do PDF or PDF/A but this is MUCH slower. When I ingest documents, it must go fast. The jpg files are all written to a folder on the microsd card of a RaspberryPi (v2 ordered). 
Some documents might be multipage PDFs (ex: manuals or PDFs received by mail)
2) OCR and transformation to PDF/A 
My scanfolder script running as daemon on the raspberry gets file system notifications and once all pages (jpg) have been received, then it calls the OCRmyPDF with all jpg in the right order. That part works fine. 
OCRmyPDF then works out the jpg set and creates one PDF/A and validates it with the Java stuff. 
It also creates a few sidecar files (OCR text, low weight jpg, validation result text). All this is written onto a Synology encrypted folder. 
This part runs in the background and I don't care if it takes long (the scan folder script can be configured to work in FIFO or LIFO mode). My raspberry is anyhow running 24/7. The B+ handles 1 page per minute with the v1.x of OCRmyPDF. The Raspberry 2B with your enhancements should do around 10 pages a minutes. 
3) The last part of the workflow is done "from anywhere" mostly from a smartphone or tablet. This review and file process will be made as clever but still assisted by a human. There will be date guessing, tag and title proposal. Last step being the symlink forest ;-)

The most important thing to understand is that this is not a linear process:
1) I scan. This must be fast and brain less. Just scan and forget. 
2) My raspberry slave transform to a PDFs. I don't care if it works day and nights. 
3) Later, anytime when waiting in a queue at the supermarket, at the doctor, ..., I sort the PDFs with a few taps on my smartphone. 

So you probably have a better view of my mad process ;-)
Note: Why take 3 days filing your documents when you can spend days and night scripting to get it done automatically ;-)

**Comment by zorglups** [comment]
@jbarlow83
I re-read  your comment and ... found your fork.
I'll go there and read your work.

**Comment by fritz-hh** [comment]
As I already wrote, I won't be able to invest much time in OCRmyPDF in the next months. As OCRmyPDF is used by quite many people, I would like like the development to continue, and I think it would be best if the development would continue to take place in this main repository.
Therefore you be open for transferring the leadersip for the project to somebody else.
@jbarlow83 : Would you be interested in taking the lead of OCRmyPDF development? As you are the main contributor, I think you would be the right person for that. I would provide you commit rights on the project (I never did it, but I think it should be possible). Would you be interessted?

**Comment by jbarlow83** [comment]
@fritz-hh - yes, I am interested and I think that makes sense for the moment anyway.

**Comment by fritz-hh** [comment]
@jbarlow83 - I added you in the list of collaborators. Hoping it gives you the required rights. If not, just tell me.

**Comment by zorglups** [comment]
Great !!! I'm really happy to see that this project stays alive. I was a
bit said with the idea that I would invest time on my own copy of this.
I'll start working on the OCRmyPDF.py and will submit it for your review
when I'm happy with it.

(I must admit that I'm quite busy too so my responsivness might varies a
lot. Hopefully you will forgive me.)

2015-03-18 21:09 GMT+01:00 fritz-hh <notifications@github.com>:

**Comment by jbarlow83** [comment]
Rough plan:
- use Python 3.4
- translate OCRmyPDF.sh to ocrmypdf.py - it should work as a drop-in replacement for the shell script and not change the way the two processes communicate (that is ocrmypdf.py would still rely on GNU parallel and launching ocrpage.py in a subprocess)
- write some test code and make sure .sh and .py are reasonably equivalent
- then functionally combine the two scripts so that they communicate directly and work together, dropping GNU parallel
- then start packaging for distribution as a PyPI module or similar

@zorglups : Thoughts?

**Comment by zorglups** [comment]
OK. As you said in the other thread, I'll work in the develop branch of the main repository.

* Python 3.4
* translation of OCPmyPDF.sh to ocrmypdf.py "as is". The only thing I would like to change is the dependency check. I would prefer that the dependencies are checked based on the options used to launch the script. Not everyone wants to have unpaper or java validation and on some platform, some modules may be painful to install. OCRmyPDF can already do a really good job without those addons. This led me to edit the script to comment some of the current checks on my Raspberry project.

The test code can already be done by anyone as the options will be the same. Only the script name will be different.

Combining can sure be done later. I'm having a look at ruffus and will probably use it.
We might drop other things than parallel but some binary modules are easier to get on any platform than specialized pdf modules. So it is a trade off. 
Do you think some binary are worth replacing them by modules (apart from parallel) ?

As said earlier, I'm starting with Python and my time is rather limited for the moment but I'm confident I can reasonably progress. Let me know if it is a problem for you.

**Comment by jbarlow83** [comment]
Yes, definitely check optional dependencies only when required. (And ideally, we'd check mandatory dependencies at install time only.)

My plan assumes we'd ultimately use ruffus to run the whole pipeline but only at the "combined" stage. It would certainly work to use a ruffus pipeline to split the PDF and call ocrpage.py on each in its own 
process. The drawback is that the debug trace of a nested ruffus pipeline will be messy, 

I'd like to replace some of the binary modules (subprocess calls) with Python modules or API calls to the C library. The benefit is that Python's pip and packaging system does a terrific job at cross platform dependencies, and some Python packages can resolve their binary dependencies on their own or tell the user how to (less work for us). Also, some of the binaries in use currently have superior Python alternatives (poppler, imagemagick). Some binary dependencies won't go away that easily (JHOVE, Ghostscript).

**Comment by jbarlow83** [comment]
@zorglups When do you think you be able to upload something to a private repository?

**Comment by zorglups** [comment]
Hello,

Sorry for the looong silence. 
Can you contact me on ehyvehillu-5548@yopmail.com ?

This way, we can arrange and when I hesitate at some point we can chat a bit. 

Pierre

**Comment by jbarlow83** [comment]
Done
